### PR TITLE
Update to superagent 1.6.1

### PR DESCRIPTION
**Pull request by holm**
Simply updates the dependency

### CODE REVIEW

**Comment by MichielDeMey** [comment]
+1

**Comment by mikelax** [comment]
Build is breaking because of node v0.8. 
I am in favor of dropping support for 0.8. I see no reason to continue support it. Does anyone disagree? 
I would then be in favor of dropping support for .10 and .12 around the April timeframe. 

Can you also up the version ^1.7.2 for me being pedantic?

**Comment by MichielDeMey** [comment]
I agree on dropping 0.8 support.

**Comment by mikelax** [comment]
Actually closing this as it's a dup of #302. More activity on that PR.

**Pull request closed without merging**
