### PR TITLE
Add a .host() method to set a host other than 127.0.0.1

### PR DESCRIPTION
**Pull request by mikec**
This allows you to set the server hostname before making a
request. If no hostname is set then it defaults to 127.0.0.1

### CODE REVIEW

**Comment by sandelius** [comment]
yes yes yes

**Comment by shults** [comment]
If somebody looks for an opportunity virtual hosts testing. My solution is below.

```javascript

function createVhostTester(app, vhost) {
  const real = supertest(app);
  const proxy = {};

  Object.keys(real).forEach(methodName => {
    proxy[methodName] = function() {
      return real[methodName]
        .apply(real, arguments)
        .set('host', vhost);
    }
  });

  return proxy;
}

var api = createVhostTester(appInstance, 'api.example.com');
var appTest = createVhostTester(appInstance, 'app.example.com');

```

**Comment by saintedlama** [comment]
@mikelax this PR could fix problems with IP V6 as well since one could pass ::1 as address :+1:

**Comment by lpil** [comment]
Hello! Is it likely this will get merged?

**Comment by jobackman** [comment]
Nice work! I would also love for this to be a feature in supertest 👍

**Comment by michaelBenin** [comment]
This is a great feature needed. Please consider merging. Ping.

**Comment by atomantic** [comment]
@shults your solution worked perfectly for me :)

**Comment by rockaBe** [comment]
Will this PR ever be considered to be merged? It's 1.5 years old now .....

**Comment by papakai** [comment]
+1

**Comment by cianclarke** [comment]
+1

**Comment by mikec** [comment]
@mikelax I fixed the conflicts and build errors, can this be merged?

**Comment by elvizcacho** [comment]
+1

**Comment by ozangds** [comment]
+1

**Comment by papakai** [comment]
guys, any update on this? Would be very great to see this added soon...

**Comment by lauzierj** [comment]
I believe you can do this using the example below:

```
supertest(app)
  .get('/path/to/thing')
  .set('host', 'api.example.com');
```

Express 4 then shows req.subdomains as ['api'].

**Comment by chrisveness** [comment]
+1

**Comment by papakai** [comment]
@lauzierj many thanks for providing that example, worked nicely. So many people waiting for it and it got already added. No idea, maybe not documented? At least I had not found anything at the time I was looking for that feature.

**Comment by yadahung** [comment]
+1

**Comment by rimiti** [comment]
Thank you for your contributions. 
This feature will be include in the next release.

**Comment by rimiti** [comment]
I merge it into `release-v3.1.0`.

**Pull request merged**
