### PR TITLE
Release v3.1.0

### PR DESCRIPTION
**Pull request by rimiti**
Hello,

Preparation of v3.1.0 release. 💥 ❤️ 

**RELEASE NOTE**
- #473 (@pedro-otero)
- #472 (@rimiti)
- #470 (@levioza)
- #446 (@bkeepers)
- #418 (@kevinburke)
- #297 (@mikec)
- #275 (@reallistic)

Regards, 
🦄

### CODE REVIEW

**Comment by rimiti** [comment]
Release preparation done, I need your reviews to merge and publish it.

**Comment by mgcrea** [comment]
@rimiti any chance you could release as `v3.1.0-beta.0` so that anyone can easily test it and get more feedback from the field?

**Comment by vjustov** [comment]
Any chance we could squish #453 in here @rimiti ?

**Comment by rimiti** [comment]
Thanks @mikelax ! 👍 
For the moment, I just can merge, not publishing.

**Comment by rimiti** [comment]
@mikelax Can you give me the npm access to publish this new version ?

**Comment by mikelax** [comment]
@rimiti I added you as a maintainer to npm. 
Also I did merge this PR, publish a new version here on github and published v3.1.0 to npm!! 🚀 

Thanks for the help in jumpstarting dev again.

**Comment by rimiti** [comment]
You'r welcome. ;)

**Comment by mikelax** [comment]
@rimiti  I just checked and noticed that for me one of the new tests are failing, this one:

`should set request hostname`
I am getting a timeout on the test. I tried changing the `done();` to:  `return done(err);` but the test still timed out.

**Comment by markstos** [comment]
What about #453? @vjustov asked about including it in this release 17 days ago, but there was no response for the relesase.

**Pull request merged**
