### PR TITLE
Added note about testing against HTTPS servers [ci skip]

### PR DESCRIPTION
**Pull request by tejashah88**
Addresses issues #396 and #146

### CODE REVIEW

**Comment by tejashah88** [comment]
@rimiti

**Comment by gjohnson** [comment]
Could also be addressed by #549.

**Comment by tejashah88** [comment]
@gjohnson Looks quite promising. I'll run a few tests to see how well this works and make a new PR to use the new feature.

**Comment by rimiti** [comment]
Is anyone could upgrade superagent ? I'm currently busy on others projects, but I can provides some help if needed.

**Comment by tejashah88** [comment]
@rimiti I just opened #553 to address updating superagent.

**Pull request closed without merging**
