### PR TITLE
Just jump to 1.0.0 already.

### PR DESCRIPTION
**Pull request by aredridel**
Let's get that semver goodness!

### CODE REVIEW

**Comment by ilanbiala** [comment]
Kind of makes sense, supertest is used by thousands of people....and it's pretty production-ready.

**Comment by jonathanong** [comment]
i would say superagent should be v1 first. @aredridel did you want to maintain these modules?

**Comment by aredridel** [comment]
I can certainly help.

**Comment by defunctzombie** [comment]
@aredridel Which modules can you help with? superagent? supertest?

**Comment by aredridel** [comment]
Yeah, I can certainly help with both. We use both at work.

**Comment by defunctzombie** [comment]
@aredridel awesome! Can you join the socket.io slack (http://socket.io/slack/) and we can chat about the items I have been poking at.

**Pull request closed without merging**
