### PR TITLE
Update to latest superagent which has a fixed cookiejar.

### PR DESCRIPTION
**Pull request by andyburke**
This updates to the latest superagent, which includes a cookiejar that addresses some bugs.

### CODE REVIEW

**Comment by awochna** [comment]
I also have encountered bugs in the current version of supertest that really come from the older version of superagent it's using.

+1 for merger!

**Comment by andrenarchy** [comment]
+1 for updating the `superagent` dependency. Actually, why does `supertest` use `~` dependencies? We wouldn't need this kind of PR with `^` dependencies (which means: use latest version with matching major version number – which should guarantee compatibility).

**Comment by nschloe** [comment]
+1 For `^1.0.0`.

**Comment by andrenarchy** [comment]
Any updates?

**Comment by zensh** [comment]
+1 for superagent v1.7.2

**Comment by andrenarchy** [comment]
Since this repo seems to be abandoned, we can use one of the forks with updated dependencies, see [here](https://github.com/awochna/supertest) and [here](https://github.com/peakon/supertest).

**Comment by mikelax** [comment]
Sorry I have been absent for a while, I'm back and can get this merged in. 
Can you also up the version ^1.7.2 for me being pedantic?

**Comment by andyburke** [comment]
Done.

**Comment by andyburke** [comment]
I am excited to back out my horrible postinstall hax. :tada:

**Pull request merged**
