### PR TITLE
Call this._setDefaults to set agent defaults

### LINKED ISSUE #538: Test agent is not setting defaults for requests
The agent returned by supertest doesn't apply the saved settings when a request is made:

```js
const supertest = require('supertest')

const request = supertest.agent(app)
                      .set('Content-Type', 'application/json')

const ret = await request.post('/some/api').send('{"some": "JSON"}')
// body is not read as json at the API
```

It's because there's a line missing that calls the `this._setDefault(req)` method in the [Test Agent](https://github.com/visionmedia/supertest/blob/master/lib/agent.js#L60)

### PR DESCRIPTION
**Pull request by ozzywalsh**
Fixes #538 

Suggestions welcome. :smile: 

Especially the tests.

### CODE REVIEW

**Comment by bdharrington7** [comment]
@rimiti Can this get into the next update?

**Comment by ozzywalsh** [comment]
@rimiti As @bdharrington7 said, it has been a while.

Can this be merged? I am happy to make any changes if there are any problems.

**Comment by rimiti** [comment]
Thanks @ozzywalsh and @bdharrington7 for your contribution. This nice feature has been merged and released:

https://github.com/visionmedia/supertest/releases/tag/v4.0.0

🚀

**Comment by noinkling** [comment]
Strange, there was already a a PR open since the end of 2017 with this exact same change: #453

How come this one was merged so fast but that one sat languishing?

Well thanks for merging this regardless.

**Comment by rimiti** [comment]
Because this PR was more recent and without conflicts. 🚀

**Pull request merged**
