### PR TITLE
Set host header instead of host in url

### PR DESCRIPTION
**Pull request by selaux**
Fixes https://github.com/visionmedia/supertest/issues/514

### CODE REVIEW

**Comment by mszkwsk** [comment]
Hi guys!

Can you update me on the status of this PR? We'd love to have such feature implemented in supertest!

**Comment by vamsys** [comment]
Hi, can we have this merged? would help a lot.

**Comment by Austio** [comment]
@niftylettuce Is there anything that i can do to help this PR become merged?

**Comment by niftylettuce** [comment]
The tests look botched in your PR, please fix them

**Comment by Va1** [comment]
please, let's get this merged. any updates on what's the status?

**Comment by niftylettuce** [comment]
I don't have access to supertest so I can't merge

**Comment by Va1** [comment]
@niftylettuce are you, perhaps, aware of someone who has access and is available?

**Comment by Va1** [comment]
@niftylettuce thank you!

**Comment by Va1** [comment]
@niftylettuce any news?

**Comment by niftylettuce** [comment]
I will reach out again

**Comment by rimiti** [comment]
@niftylettuce

I have just give you all accesses.
Thanks for your help 🙏

**Comment by rimiti** [comment]
> I am waiting on npm ownership, once I have that I will follow up. I think we'll do a ~minor~ major semver bump here unless you think otherwise.

NPM access given.

**Comment by niftylettuce** [comment]
Released https://github.com/visionmedia/supertest/releases/tag/v6.0.0!

**Comment by Va1** [comment]
thank you guys @niftylettuce @rimiti much appreciated!

**Pull request merged**
