### PR TITLE
Use === instead of == where guaranteed to be a string

### PR DESCRIPTION
**Pull request by knownasilya**

### CODE REVIEW

**Comment by ilanbiala** [comment]
Is there any reason not to merge this in?

**Comment by jonathanong** [comment]
this has no functional differences. it's just stylistic. i'm a `===` kind of person, but i care much more about git diffs.

**Comment by knownasilya** [comment]
Hardly styalistic, since a `==` performs a 'cast' behind the scenes to make the objects similar if they aren't, thus performance is better with `===`.

**Comment by invernizzie** [comment]
`typeof` returns string. This makes no sense.

**Comment by knownasilya** [comment]
@invernizzie Ah yes. Although, as a library, the best standards should be practices, and strict equality is one of those standards. It's best to use it everywhere (as you are able), otherwise there won't be any consistency.

**Pull request closed without merging**
