### PR TITLE
Superagent downgrading

### PR DESCRIPTION
**Pull request by rimiti**
Hello,

To quickly unblock the situation, I propose to downgrade the superagent version.

**Details of this PR:**
- Test included to assert using promises (fail with superagent v4.x). 
- Superagent downgraded to "^3.8.3".

**Related issues:**
- #557
- #556

**Current investigation:**
The line causing this promise issue in superagent: https://github.com/visionmedia/superagent/blob/master/lib/request-base.js#L245

If this line is commented, supertest works fine with superagent v4. 

_Note: I am very busy to investigate for now, if anyone has time to work on a new pull request (regarding the safe update of superagent), it would be great. Otherwise I will do it as soon as I have time;_

### CODE REVIEW

**Comment by rimiti** [comment]
@gjohnson What do you think about that? 🤓

**Comment by gjohnson** [comment]
@rimiti I'll let you merge and release. We'll discuss a path forward on slack.

**Comment by rimiti** [comment]
it should have been tagged as **v4.0.0-alpha.1** but we can rewrite the past.

**Comment by Floby** [comment]
Thank all of you. At least this was published on a major/breaking version anyway. Could be worse. :)

**Comment by bajtos** [comment]
FWIW, I believe the actual root cause of the problem is in superagent and should be already fixed by my pull request https://github.com/visionmedia/superagent/pull/1468. Once a new version of superagent is released, we should be good to use `superagent@4` in supertest again.

**Comment by artparks** [comment]
any news on upgrading this?

**Comment by mdhornet90** [comment]
Checked out `supertest` on my machine and updated its dependency on `superagent` first to 4.0.0, and confirmed that there was a failing test due to a timeout being exceeded (`should assert using promises`). I then changed the dependency version to 5.1.0 (which includes @bajtos fix) and confirmed that all tests pass. Can this move forward or does there need to be more verification?

**Comment by rimiti** [comment]
I'll try to pre-release a version today. 
Thanks @bajtos and @mdhornet90

**Pull request merged**
